### PR TITLE
Add thumbnails to sample data sets

### PR DESCRIPTION
**Pull request by lassoan**
Thumbnails are now displayed in Sample Data module:

image

### CODE REVIEW

**Comment by rbumm** [comment]
Great masks ... How did you produce them? Masking is not easy to solve. I just analyzed a severe COVID case in which the collapsed lung areas are not recognized by my most recent mask algorithm from the other extension.

**Comment by lassoan** [comment]
This is the mask that you provided. I'll add a new issue to discuss segmentation.

**Comment by rbumm** [comment]
Thaanks.
I am so unexperienced with GIT ... just overwrote my README.md from yesterday because I pushed from the hospital. 
Sorry.

**Comment by lassoan** [comment]
You can prevent overwriting of the history (losing data) by enabling protected branch for your master branch in your repository setting. We are experienced with git but still enable this feature because accidents can happen.

**Pull request merged**
